---
- name: Install and start Nginx on web servers
  hosts: webservers
  become: true
  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Enable and start Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Verify Nginx is running
      shell: systemctl is-active nginx
      register: nginx_status

    - name: Print Nginx status
      debug:
        var: nginx_status.stdout
